### ISSUE TITLE
AZ-304 challenge modules checklist

### ISSUE THREAD

**Issue by Ungerfall** [Ungerfall/learning-azure#1]
# AZ-304

1. [x] [Connect your on-premises network to Azure with VPN Gateway](https://docs.microsoft.com/en-us/learn/modules/connect-on-premises-network-with-vpn-gateway/)
2. [x] [Connect your on-premises network to the Microsoft global network by using ExpressRoute](https://docs.microsoft.com/en-us/learn/modules/connect-on-premises-network-with-expressroute/)
3. [x] [Secure and isolate access to Azure resources by using network security groups and service endpoints](https://docs.microsoft.com/en-us/learn/modules/secure-and-isolate-with-nsg-and-service-endpoints/)
4. [x] [Distribute your services across Azure virtual networks and integrate them by using virtual network peering](https://docs.microsoft.com/en-us/learn/modules/integrate-vnets-with-vnet-peering/)
5. [x] [Enhance your service availability and data locality by using Azure Traffic Manager](https://docs.microsoft.com/en-us/learn/modules/distribute-load-with-traffic-manager/)
6. [x] [Improve application scalability and resiliency by using Azure Load Balancer](https://docs.microsoft.com/en-us/learn/modules/improve-app-scalability-resiliency-with-load-balancer/)
7. [x] [Load balance your web service traffic with Application Gateway](https://docs.microsoft.com/en-us/learn/modules/load-balance-web-traffic-with-application-gateway/)
8. [x] [Manage and control traffic flow in your Azure deployment with routes](https://docs.microsoft.com/en-us/learn/modules/control-network-traffic-flow-with-routes/)
9. [x] [Design an IP addressing schema for your Azure deployment](https://docs.microsoft.com/en-us/learn/modules/design-ip-addressing-for-azure/)
10. [ ] [Design a hybrid network architecture on Azure](https://docs.microsoft.com/en-us/learn/modules/design-a-hybrid-network-architecture/)
11. [ ] [Centralize your core services by using hub and spoke Azure virtual network architecture](https://docs.microsoft.com/en-us/learn/modules/hub-and-spoke-network-architecture/)
12. [ ] [Monitor and troubleshoot your end-to-end Azure network infrastructure by using network monitoring tools](https://docs.microsoft.com/en-us/learn/modules/troubleshoot-azure-network-infrastructure/)
13. [x] [Choose a data storage approach in Azure](https://docs.microsoft.com/en-us/learn/modules/choose-storage-approach-in-azure/)
14. [x] [Create an Azure Storage account](https://docs.microsoft.com/en-us/learn/modules/create-azure-storage-account/)
15. [x] [Upload, download, and manage data with Azure Storage Explorer](https://docs.microsoft.com/en-us/learn/modules/upload-download-and-manage-data-with-azure-storage-explorer/)
16. [x] [Connect an app to Azure Storage](https://docs.microsoft.com/en-us/learn/modules/connect-an-app-to-azure-storage/)
17. [x] [Make your application storage highly available with read-access geo-redundant storage](https://docs.microsoft.com/en-us/learn/modules/ha-application-storage-with-grs/)
18. [x] [Secure your Azure Storage account](https://docs.microsoft.com/en-us/learn/modules/secure-azure-storage-account/)
19. [ ] [Store and share files in your app with Azure Files](https://docs.microsoft.com/en-us/learn/modules/store-and-share-with-azure-files/)
20. [x] [Choose the right disk storage for your virtual machine workload](https://docs.microsoft.com/en-us/learn/modules/choose-the-right-disk-storage-for-vm-workload/)
21. [x] [Monitor, diagnose, and troubleshoot your Azure storage](https://docs.microsoft.com/en-us/learn/modules/monitor-diagnose-and-troubleshoot-azure-storage/)
22. [ ] [Explore Azure compute services](https://docs.microsoft.com/en-us/learn/modules/azure-compute-fundamentals/)
23. [ ] [Manage virtual machines with the Azure CLI](https://docs.microsoft.com/en-us/learn/modules/manage-virtual-machines-with-azure-cli/)
24. [ ] [Choose a compute provisioning solution for your application](https://docs.microsoft.com/en-us/learn/modules/choose-compute-provisioning/)
25. [ ] [Deploy Azure infrastructure by using JSON ARM templates](https://docs.microsoft.com/en-us/learn/modules/create-azure-resource-manager-template-vs-code/)
26. [ ] [Deploy Azure virtual machines from VHD templates](https://docs.microsoft.com/en-us/learn/modules/deploy-vms-from-vhd-templates/)
27. [ ] [Build a scalable application with virtual machine scale sets](https://docs.microsoft.com/en-us/learn/modules/build-app-with-scale-sets/)
28. [ ] [Choose the best Azure service to automate your business processes](https://docs.microsoft.com/en-us/learn/modules/choose-azure-service-to-integrate-and-automate-business-processes/)
29. [ ] [Introduction to high-performance computing (HPC) on Azure](https://docs.microsoft.com/en-us/learn/modules/intro-to-hpc/)
30. [ ] [Run parallel tasks in Azure Batch with the Azure CLI](https://docs.microsoft.com/en-us/learn/modules/run-parallel-tasks-in-azure-batch-with-the-azure-cli/)
31. [ ] [Control and organize Azure resources with Azure Resource Manager](https://docs.microsoft.com/en-us/learn/modules/control-and-organize-with-azure-resource-manager/)
32. [x] [Build a cloud governance strategy on Azure](https://docs.microsoft.com/en-us/learn/modules/build-cloud-governance-strategy-azure/)
33. [ ] [Design a holistic monitoring strategy on Azure](https://docs.microsoft.com/en-us/learn/modules/design-monitoring-strategy-on-azure/)
34. [ ] [Improve incident response with alerting on Azure](https://docs.microsoft.com/en-us/learn/modules/incident-response-with-alerting-on-azure/)
35. [ ] [Analyze your Azure infrastructure by using Azure Monitor logs](https://docs.microsoft.com/en-us/learn/modules/analyze-infrastructure-with-azure-monitor-logs/)
36. [ ] [Explore Azure database and analytics services](https://docs.microsoft.com/en-us/learn/modules/azure-database-fundamentals/)
37. [ ] [Provision an Azure SQL database to store application data](https://docs.microsoft.com/en-us/learn/modules/provision-azure-sql-db/)
38. [ ] [Scale multiple Azure SQL Databases with SQL elastic pools](https://docs.microsoft.com/en-us/learn/modules/scale-sql-databases-elastic-pools/)
39. [ ] [Migrate your relational data stored in SQL Server to Azure SQL Database](https://docs.microsoft.com/en-us/learn/modules/migrate-sql-server-relational-data/)
40. [ ] [Develop and configure an ASP.NET application that queries an Azure SQL database](https://docs.microsoft.com/en-us/learn/modules/develop-app-that-queries-azure-sql/)
41. [ ] [Create an Azure Cosmos DB database built to scale](https://docs.microsoft.com/en-us/learn/modules/create-cosmos-db-for-scale/)
42. [ ] [Distribute your data globally with Azure Cosmos DB](https://docs.microsoft.com/en-us/learn/modules/distribute-data-globally-with-cosmos-db/)
43. [ ] [Insert and query data in your Azure Cosmos DB database](https://docs.microsoft.com/en-us/learn/modules/access-data-with-cosmos-db-and-sql-api/)
44. [ ] [Design a data warehouse with Azure Synapse Analytics](https://docs.microsoft.com/en-us/learn/modules/design-azure-sql-data-warehouse/)
45. [ ] [Import data into Azure Synapse Analytics by using PolyBase](https://docs.microsoft.com/en-us/learn/modules/import-data-into-asdw-with-polybase/)
46. [ ] [Create serverless logic with Azure Functions](https://docs.microsoft.com/en-us/learn/modules/create-serverless-logic-with-azure-functions/)
47. [ ] [Route and process data automatically using Logic Apps](https://docs.microsoft.com/en-us/learn/modules/route-and-process-data-logic-apps/)
48. [ ] [Choose a messaging model in Azure to loosely connect your services](https://docs.microsoft.com/en-us/learn/modules/choose-a-messaging-model-in-azure-to-connect-your-services/)
49. [x] [Communicate between applications with Azure Queue storage](https://docs.microsoft.com/en-us/learn/modules/communicate-between-apps-with-azure-queue-storage/)
50. [ ] [Enable reliable messaging for Big Data applications using Azure Event Hubs](https://docs.microsoft.com/en-us/learn/modules/enable-reliable-messaging-for-big-data-apps-using-event-hubs/)
51. [ ] [Implement message-based communication workflows with Azure Service Bus](https://docs.microsoft.com/en-us/learn/modules/implement-message-workflows-with-service-bus/)
52. [ ] [React to state changes in your Azure services by using Event Grid](https://docs.microsoft.com/en-us/learn/modules/react-to-state-changes-using-event-grid/)
53. [ ] [Expose hybrid services securely with Azure Relay](https://docs.microsoft.com/en-us/learn/modules/expose-hybrid-services-with-azure-relay/)
54. [ ] [Build a containerized web application with Docker](https://docs.microsoft.com/en-us/learn/modules/intro-to-containers/)
55. [ ] [Run Docker containers with Azure Container Instances](https://docs.microsoft.com/en-us/learn/modules/run-docker-with-azure-container-instances/)
56. [ ] [Build and store container images with Azure Container Registry](https://docs.microsoft.com/en-us/learn/modules/build-and-store-container-images/)
57. [ ] [Host a web application with Azure App Service](https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service/)
58. [ ] [Deploy and run a containerized web app with Azure App Service](https://docs.microsoft.com/en-us/learn/modules/deploy-run-container-app-service/)
59. [ ] [Introduction to Azure Kubernetes Service](https://docs.microsoft.com/en-us/learn/modules/intro-to-azure-kubernetes-service/)
60. [ ] [Work with mutable and partial data in Azure Cache for Redis](https://docs.microsoft.com/en-us/learn/modules/work-with-mutable-and-partial-data-in-a-redis-cache/)
61. [ ] [Publish and manage your APIs with Azure API Management](https://docs.microsoft.com/en-us/learn/modules/publish-manage-apis-with-azure-api-management/)
62. [ ] [Improve the performance of an API by adding a caching policy in Azure API Management](https://docs.microsoft.com/en-us/learn/modules/improve-api-performance-with-apim-caching-policy/)
63. [ ] [Protect your APIs on Azure API Management](https://docs.microsoft.com/en-us/learn/modules/protect-apis-on-api-management/)
64. [ ] [Control authentication for your APIs with Azure API Management](https://docs.microsoft.com/en-us/learn/modules/control-authentication-with-apim/)
65. [ ] [Expose multiple Azure Function apps as a consistent API by using Azure API Management](https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/)
66. [ ] [Design your migration to Azure](https://docs.microsoft.com/en-us/learn/modules/design-your-migration-to-azure/)
67. [ ] [Protect your on-premises infrastructure from disasters with Azure Site Recovery](https://docs.microsoft.com/en-us/learn/modules/protect-on-premises-infrastructure-with-azure-site-recovery/)
68. [x] [Design your site recovery solution in Azure](https://docs.microsoft.com/en-us/learn/modules/design-your-site-recovery-solution-in-azure/)
69. [ ] [Protect your Azure infrastructure with Azure Site Recovery](https://docs.microsoft.com/en-us/learn/modules/protect-infrastructure-with-site-recovery/)
70. [ ] [Protect your virtual machines by using Azure Backup](https://docs.microsoft.com/en-us/learn/modules/protect-virtual-machines-with-azure-backup/)
71. [ ] [Back up and restore your Azure SQL database](https://docs.microsoft.com/en-us/learn/modules/backup-restore-azure-sql/)
72. [ ] [Dynamically meet changing web app performance requirements with autoscale rules](https://docs.microsoft.com/en-us/learn/modules/app-service-autoscale-rules/)
73. [ ] [Scale an App Service web app to efficiently meet demand with App Service scale up and scale out](https://docs.microsoft.com/en-us/learn/modules/app-service-scale-up-scale-out/)
74. [ ] [Design a geographically distributed application](https://docs.microsoft.com/en-us/learn/modules/design-a-geographically-distributed-application/)
75. [ ] [Intro to Azure Front Door](https://docs.microsoft.com/en-us/learn/modules/intro-to-azure-front-door/)
76. [ ] [Load balance HTTP traffic in Azure](https://docs.microsoft.com/en-us/learn/modules/load-balancing-https-traffic-azure/)
